# Generated by Django 6.0.7 on 2026-08-22 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lead', '0003_conversation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('collecting_info', 'Collecting Info'), ('waiting_for_human', 'Waiting for Human'), ('ready_for_review', 'Ready for Review'), ('approved', 'Approved'), ('closed', 'Closed')], db_index=True, default='collecting_info', max_length=40)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('tattoo_idea', models.TextField(blank=True, default='')),
                ('style_tags', models.JSONField(blank=True, default=list)),
                ('placement', models.CharField(blank=True, default='', max_length=255)),
                ('size_estimate_cm', models.CharField(blank=True, default='', max_length=100)),
                ('color_preference', models.CharField(blank=True, default='', max_length=100)),
                ('suggested_artist', models.CharField(blank=True, default='', max_length=100)),
                ('confidence_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=20)),
                ('ai_reasoning', models.TextField(blank=True, default='')),
                ('missing_information', models.JSONField(blank=True, default=list)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=20)),
                ('latest_draft_reply', models.TextField(blank=True, default='')),
                ('latest_raw_ai_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_requests', to='lead.conversation')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intake_requests', to='lead.lead')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(default='analyze', max_length=100)),
                ('tattoo_idea', models.TextField(blank=True, default='')),
                ('style_tags', models.JSONField(blank=True, default=list)),
                ('placement', models.CharField(blank=True, default='', max_length=255)),
                ('size_estimate_cm', models.CharField(blank=True, default='', max_length=100)),
                ('color_preference', models.CharField(blank=True, default='', max_length=100)),
                ('suggested_artist', models.CharField(blank=True, default='', max_length=100)),
                ('confidence_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=20)),
                ('ai_reasoning', models.TextField(blank=True, default='')),
                ('missing_information', models.JSONField(blank=True, default=list)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=20)),
                ('draft_reply', models.TextField(blank=True, default='')),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='lead.lead')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_analyses', to='lead.message')),
                ('intake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='intake.intakerequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='intakerequest',
            index=models.Index(fields=['lead', 'is_active'], name='intake_inta_lead_id_20b7b5_idx'),
        ),
        migrations.AddIndex(
            model_name='intakerequest',
            index=models.Index(fields=['conversation', 'is_active'], name='intake_inta_convers_3ff465_idx'),
        ),
        migrations.AddIndex(
            model_name='intakerequest',
            index=models.Index(fields=['risk_level'], name='intake_inta_risk_le_c34e6c_idx'),
        ),
        migrations.AddIndex(
            model_name='intakerequest',
            index=models.Index(fields=['status'], name='intake_inta_status_df9faa_idx'),
        ),
        migrations.AddIndex(
            model_name='aianalysis',
            index=models.Index(fields=['intake', 'created_at'], name='intake_aian_intake__6487a0_idx'),
        ),
        migrations.AddIndex(
            model_name='aianalysis',
            index=models.Index(fields=['lead', 'created_at'], name='intake_aian_lead_id_6b070c_idx'),
        ),
        migrations.AddIndex(
            model_name='aianalysis',
            index=models.Index(fields=['message'], name='intake_aian_message_3c4dc3_idx'),
        ),
        migrations.AddIndex(
            model_name='aianalysis',
            index=models.Index(fields=['risk_level'], name='intake_aian_risk_le_99e3d9_idx'),
        ),
    ]
