# Generated by Django 6.0.7 on 2026-08-22 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_outlookaccount_outlookaccesstoken_and_more'),
        ('intake', '0001_initial'),
        ('lead', '0003_conversation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumanDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approve_ai_reply', 'Approve AI Reply'), ('reject', 'Reject'), ('assign_artist', 'Assign Artist'), ('needs_manual_reply', 'Needs Manual Reply'), ('artist_reply', 'Artist Reply')], db_index=True, max_length=40)),
                ('note', models.TextField(blank=True, default='')),
                ('telegram_chat_id', models.BigIntegerField(blank=True, null=True)),
                ('telegram_message_id', models.BigIntegerField(blank=True, null=True)),
                ('telegram_callback_id', models.CharField(blank=True, default='', max_length=255)),
                ('raw_update', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramMessageLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('group_review', 'Group Review'), ('artist_assignment', 'Artist Assignment'), ('client_update', 'Client Update'), ('bot_info', 'Bot Info')], db_index=True, max_length=40)),
                ('telegram_chat_id', models.BigIntegerField(db_index=True)),
                ('telegram_message_id', models.BigIntegerField(db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('raw_message', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='intakerequest',
            name='last_incoming_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='latest_for_intakes', to='lead.message'),
        ),
        migrations.AddField(
            model_name='intakerequest',
            name='outlook_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_requests', to='core.outlookaccount'),
        ),
        migrations.AddField(
            model_name='intakerequest',
            name='outlook_user_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='intakerequest',
            name='source',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('outlook', 'Outlook'), ('other', 'Other')], db_index=True, default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='intakerequest',
            name='whatsapp_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_requests', to='core.whatsappaccount'),
        ),
        migrations.AlterField(
            model_name='intakerequest',
            name='status',
            field=models.CharField(choices=[('collecting_info', 'Collecting Info'), ('waiting_for_human', 'Waiting for Human'), ('ready_for_review', 'Ready for Review'), ('assigned', 'Assigned'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('closed', 'Closed')], db_index=True, default='collecting_info', max_length=40),
        ),
        migrations.CreateModel(
            name='ArtistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('telegram_user_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('telegram_chat_id', models.BigIntegerField(blank=True, null=True)),
                ('can_approve', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('specialties', models.JSONField(blank=True, default=list)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='intake_arti_is_acti_0e6873_idx'), models.Index(fields=['can_approve'], name='intake_arti_can_app_ef79a3_idx')],
            },
        ),
        migrations.AddField(
            model_name='intakerequest',
            name='assigned_artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_intakes', to='intake.artistprofile'),
        ),
        migrations.AddIndex(
            model_name='intakerequest',
            index=models.Index(fields=['assigned_artist', 'is_active'], name='intake_inta_assigne_61ccba_idx'),
        ),
        migrations.AddIndex(
            model_name='intakerequest',
            index=models.Index(fields=['source'], name='intake_inta_source_c71745_idx'),
        ),
        migrations.AddField(
            model_name='humandecision',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='human_decisions', to='intake.artistprofile'),
        ),
        migrations.AddField(
            model_name='humandecision',
            name='assigned_artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_decisions', to='intake.artistprofile'),
        ),
        migrations.AddField(
            model_name='humandecision',
            name='intake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='human_decisions', to='intake.intakerequest'),
        ),
        migrations.AddField(
            model_name='telegrammessagelink',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_links', to='intake.artistprofile'),
        ),
        migrations.AddField(
            model_name='telegrammessagelink',
            name='intake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_links', to='intake.intakerequest'),
        ),
        migrations.AddField(
            model_name='telegrammessagelink',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_links', to='lead.lead'),
        ),
        migrations.AddIndex(
            model_name='humandecision',
            index=models.Index(fields=['intake', 'created_at'], name='intake_huma_intake__d53c72_idx'),
        ),
        migrations.AddIndex(
            model_name='humandecision',
            index=models.Index(fields=['actor', 'created_at'], name='intake_huma_actor_i_4da806_idx'),
        ),
        migrations.AddIndex(
            model_name='humandecision',
            index=models.Index(fields=['action'], name='intake_huma_action_15e330_idx'),
        ),
        migrations.AddIndex(
            model_name='telegrammessagelink',
            index=models.Index(fields=['telegram_chat_id', 'telegram_message_id'], name='intake_tele_telegra_f1ea75_idx'),
        ),
        migrations.AddIndex(
            model_name='telegrammessagelink',
            index=models.Index(fields=['intake', 'purpose'], name='intake_tele_intake__c48b51_idx'),
        ),
        migrations.AddIndex(
            model_name='telegrammessagelink',
            index=models.Index(fields=['artist', 'is_active'], name='intake_tele_artist__3d016d_idx'),
        ),
        migrations.AddConstraint(
            model_name='telegrammessagelink',
            constraint=models.UniqueConstraint(fields=('telegram_chat_id', 'telegram_message_id'), name='unique_telegram_message_link'),
        ),
    ]
