# Generated by Django 6.0.7 on 2026-08-23 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0002_humandecision_telegrammessagelink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humandecision',
            name='action',
            field=models.CharField(choices=[('approve_ai_reply', 'Approve AI Reply'), ('reject', 'Reject'), ('assign_artist', 'Assign Artist'), ('edit_reply', 'Edit Reply'), ('artist_reply', 'Artist Reply')], db_index=True, max_length=40),
        ),
    ]
