# Generated by Django 6.0.7 on 2026-08-23 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0003_alter_humandecision_action'),
        ('lead', '0003_conversation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('outlook', 'Outlook'), ('other', 'Other')], db_index=True, max_length=20)),
                ('action_type', models.CharField(choices=[('ai_auto_reply', 'AI Auto Reply'), ('waiting_message', 'Waiting Message'), ('hoss_approved_reply', 'Hoss Approved Reply'), ('hoss_edited_reply', 'Hoss Edited Reply'), ('artist_reply', 'Artist Reply')], db_index=True, max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('text', models.TextField(blank=True, default='')),
                ('media_items', models.JSONField(blank=True, default=list)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=500)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_actions', to='intake.artistprofile')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_actions', to='lead.conversation')),
                ('intake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_actions', to='intake.intakerequest')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_actions', to='lead.lead')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_actions', to='lead.message')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['intake', 'created_at'], name='intake_outb_intake__ceb5c2_idx'), models.Index(fields=['lead', 'created_at'], name='intake_outb_lead_id_4dfe2e_idx'), models.Index(fields=['status', 'created_at'], name='intake_outb_status_5b0afb_idx'), models.Index(fields=['action_type', 'created_at'], name='intake_outb_action__f14d8e_idx'), models.Index(fields=['source', 'created_at'], name='intake_outb_source_1ba542_idx')],
            },
        ),
    ]
