# Generated by Django 6.0.7 on 2026-08-23 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0004_outboundaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysis',
            name='pricing_reasoning',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='suggested_price',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='intakerequest',
            name='ai_suggested_price',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='intakerequest',
            name='approved_price',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='intakerequest',
            name='latest_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='intakerequest',
            name='price_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intakerequest',
            name='price_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_approved_intakes', to='intake.artistprofile'),
        ),
        migrations.AddField(
            model_name='intakerequest',
            name='price_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='humandecision',
            name='action',
            field=models.CharField(choices=[('approve_ai_reply', 'Approve AI Reply'), ('reject', 'Reject'), ('assign_artist', 'Assign Artist'), ('edit_reply', 'Edit Reply'), ('edit_price', 'Edit Price'), ('artist_reply', 'Artist Reply')], db_index=True, max_length=40),
        ),
    ]
