# Generated by Django 6.0.7 on 2026-08-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_outlookaccount_outlookaccesstoken_and_more'),
        ('intake', '0005_aianalysis_pricing_reasoning_and_more'),
        ('lead', '0004_lead_vcita_client_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysis',
            name='appointment_date',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='appointment_time',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='vcita_staff_uid',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='intakerequest',
            name='appointment_date',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='intakerequest',
            name='appointment_time',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='intakerequest',
            name='payment_reference',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='intakerequest',
            name='payment_status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('unpaid', 'Unpaid'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], db_index=True, default='unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='intakerequest',
            name='schedule_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='intakerequest',
            name='schedule_status',
            field=models.CharField(choices=[('not_scheduled', 'Not Scheduled'), ('scheduled', 'Scheduled'), ('rescheduled', 'Rescheduled'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], db_index=True, default='not_scheduled', max_length=30),
        ),
        migrations.AddField(
            model_name='intakerequest',
            name='scheduled_date',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='intakerequest',
            name='scheduled_time',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='intakerequest',
            name='vcita_booking_uid',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='humandecision',
            name='action',
            field=models.CharField(choices=[('approve_ai_reply', 'Approve AI Reply'), ('reject', 'Reject'), ('assign_artist', 'Assign Artist'), ('edit_reply', 'Edit Reply'), ('edit_price', 'Edit Price'), ('schedule', 'Schedule'), ('artist_reply', 'Artist Reply')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='outboundaction',
            name='action_type',
            field=models.CharField(choices=[('ai_auto_reply', 'AI Auto Reply'), ('waiting_message', 'Waiting Message'), ('hoss_approved_reply', 'Hoss Approved Reply'), ('hoss_edited_reply', 'Hoss Edited Reply'), ('schedule_notification', 'Schedule Notification'), ('artist_reply', 'Artist Reply')], db_index=True, max_length=40),
        ),
        migrations.AddIndex(
            model_name='intakerequest',
            index=models.Index(fields=['schedule_status'], name='intake_inta_schedul_23adaf_idx'),
        ),
        migrations.AddIndex(
            model_name='intakerequest',
            index=models.Index(fields=['payment_status'], name='intake_inta_payment_836cf8_idx'),
        ),
    ]
