# Generated by Django 6.0.7 on 2026-09-03 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0006_aianalysis_appointment_date_and_more'),
        ('vcita', '0003_vcitaservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='intakerequest',
            name='scheduled_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_intakes', to='vcita.vcitaservice'),
        ),
        migrations.AddField(
            model_name='intakerequest',
            name='scheduled_service_code',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='intakerequest',
            name='scheduled_service_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='intakerequest',
            name='scheduled_service_uid',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
