# Generated by Django 6.0.7 on 2026-09-06 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_outlookaccount_outlookaccesstoken_and_more'),
        ('intake', '0007_intakerequest_scheduled_service_and_more'),
        ('lead', '0004_lead_vcita_client_uid'),
        ('vcita', '0003_vcitaservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='intakerequest',
            name='pending_hold_date',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='intakerequest',
            name='pending_hold_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='intakerequest',
            name='pending_hold_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intakerequest',
            name='pending_hold_finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intakerequest',
            name='pending_hold_released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intakerequest',
            name='pending_hold_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_hold_intakes', to='vcita.vcitaservice'),
        ),
        migrations.AddField(
            model_name='intakerequest',
            name='pending_hold_service_code',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='intakerequest',
            name='pending_hold_service_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='intakerequest',
            name='pending_hold_service_uid',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='intakerequest',
            name='pending_hold_status',
            field=models.CharField(choices=[('none', 'None'), ('active', 'Active'), ('finalized', 'Finalized'), ('released', 'Released'), ('failed', 'Failed')], db_index=True, default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='intakerequest',
            name='pending_hold_time',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='humandecision',
            name='action',
            field=models.CharField(choices=[('approve_ai_reply', 'Approve AI Reply'), ('reject', 'Reject'), ('assign_artist', 'Assign Artist'), ('edit_reply', 'Edit Reply'), ('edit_price', 'Edit Price'), ('hold_appointment', 'Hold Appointment'), ('schedule', 'Schedule'), ('artist_reply', 'Artist Reply')], db_index=True, max_length=40),
        ),
        migrations.AddIndex(
            model_name='intakerequest',
            index=models.Index(fields=['pending_hold_status'], name='intake_inta_pending_4f1f12_idx'),
        ),
        migrations.AddIndex(
            model_name='intakerequest',
            index=models.Index(fields=['pending_hold_expires_at'], name='intake_inta_pending_e37ac6_idx'),
        ),
    ]
