# Generated by Django 6.0.7 on 2026-09-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0008_intakerequest_pending_hold_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intakerequest',
            name='pending_hold_review_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='humandecision',
            name='action',
            field=models.CharField(choices=[('approve_ai_reply', 'Approve AI Reply'), ('reject', 'Reject'), ('assign_artist', 'Assign Artist'), ('edit_reply', 'Edit Reply'), ('edit_price', 'Edit Price'), ('hold_appointment', 'Hold Appointment'), ('keep_hold', 'Keep Hold'), ('release_hold', 'Release Hold'), ('pending_hold_review', 'Pending Hold Review'), ('schedule', 'Schedule'), ('artist_reply', 'Artist Reply')], db_index=True, max_length=40),
        ),
    ]
