# Generated by Django 6.0.7 on 2026-09-06 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0009_intakerequest_pending_hold_review_notified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humandecision',
            name='action',
            field=models.CharField(choices=[('approve_ai_reply', 'Approve AI Reply'), ('reject', 'Reject'), ('assign_artist', 'Assign Artist'), ('external_artist_offer', 'External Artist Offer'), ('external_artist_accept', 'External Artist Accept'), ('external_artist_decline', 'External Artist Decline'), ('edit_reply', 'Edit Reply'), ('edit_price', 'Edit Price'), ('hold_appointment', 'Hold Appointment'), ('keep_hold', 'Keep Hold'), ('release_hold', 'Release Hold'), ('pending_hold_review', 'Pending Hold Review'), ('schedule', 'Schedule'), ('artist_reply', 'Artist Reply')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='outboundaction',
            name='action_type',
            field=models.CharField(choices=[('ai_auto_reply', 'AI Auto Reply'), ('waiting_message', 'Waiting Message'), ('hoss_approved_reply', 'Hoss Approved Reply'), ('hoss_edited_reply', 'Hoss Edited Reply'), ('schedule_notification', 'Schedule Notification'), ('external_artist_accepted', 'External Artist Accepted'), ('artist_reply', 'Artist Reply')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='telegrammessagelink',
            name='purpose',
            field=models.CharField(choices=[('group_review', 'Group Review'), ('artist_assignment', 'Artist Assignment'), ('external_artist_offer', 'External Artist Offer'), ('client_update', 'Client Update'), ('bot_info', 'Bot Info')], db_index=True, max_length=40),
        ),
        migrations.CreateModel(
            name='ExternalArtistOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('offered', 'Offered'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], db_index=True, default='offered', max_length=20)),
                ('safe_brief', models.TextField(blank=True, default='')),
                ('telegram_chat_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('telegram_message_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('client_contact_released_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('raw_update', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_artist_offers', to='intake.artistprofile')),
                ('intake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_artist_offers', to='intake.intakerequest')),
                ('offered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_artist_offers_made', to='intake.artistprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['intake', 'status'], name='intake_exte_intake__915912_idx'), models.Index(fields=['artist', 'status'], name='intake_exte_artist__18d290_idx'), models.Index(fields=['telegram_chat_id', 'telegram_message_id'], name='intake_exte_telegra_7870ff_idx')],
            },
        ),
    ]
