# Generated by Django 6.0.7 on 2026-09-07 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_outlookaccount_outlookaccesstoken_and_more'),
        ('intake', '0010_alter_humandecision_action_and_more'),
        ('lead', '0004_lead_vcita_client_uid'),
        ('vcita', '0004_vcitaaccount_external_booking_staff_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intakerequest',
            name='vcita_matter_uid',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='intakerequest',
            index=models.Index(fields=['vcita_matter_uid'], name='intake_inta_vcita_m_d73b4d_idx'),
        ),
    ]
