# Generated by Django 6.0.7 on 2026-09-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0011_intakerequest_vcita_matter_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysis',
            name='appointment_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='auto_reply_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='client_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='preferred_artist',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='tattoo_project_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='telegram_review_required',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='intakerequest',
            name='appointment_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='intakerequest',
            name='auto_reply_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='intakerequest',
            name='client_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='intakerequest',
            name='preferred_artist',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='intakerequest',
            name='tattoo_project_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='intakerequest',
            name='telegram_review_required',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
