# Generated by Django 6.0.7 on 2026-09-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0012_aianalysis_appointment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysis',
            name='request_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
