# Generated by Django 6.0.7 on 2026-09-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0013_aianalysis_request_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysis',
            name='artist_preference_mode',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='client_intent',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='complexity_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='conversation_status',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='intake_status',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='multi_entity_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='party_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='pricing_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='review_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='size_description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='size_status',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='staff_review_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='intakerequest',
            name='artist_preference_mode',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='intakerequest',
            name='client_intent',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='intakerequest',
            name='complexity_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='intakerequest',
            name='conversation_status',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='intakerequest',
            name='intake_status',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='intakerequest',
            name='multi_entity_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='intakerequest',
            name='party_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intakerequest',
            name='pricing_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='intakerequest',
            name='review_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='intakerequest',
            name='size_description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='intakerequest',
            name='size_status',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='intakerequest',
            name='staff_review_required',
            field=models.BooleanField(default=False),
        ),
    ]
