# Generated by Django 6.0.7 on 2026-08-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcita', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vcitaaccount',
            name='business_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vcitaaccount',
            name='business_uid',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vcitaaccount',
            name='default_service_uid',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vcitaaccount',
            name='default_timezone',
            field=models.CharField(default='Europe/Amsterdam', max_length=100),
        ),
        migrations.AddField(
            model_name='vcitaaccount',
            name='webhook_secret',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
