# Generated by Django 6.0.7 on 2026-09-03 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcita', '0002_vcitaaccount_business_name_vcitaaccount_business_uid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VcitaService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('vcita_service_uid', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='vcita.vcitaaccount')),
            ],
            options={
                'ordering': ['code'],
                'indexes': [models.Index(fields=['is_active', 'code'], name='vcita_vcita_is_acti_edbbcc_idx')],
                'constraints': [models.UniqueConstraint(fields=('account', 'code'), name='unique_vcita_service_code_per_account'), models.UniqueConstraint(fields=('account', 'vcita_service_uid'), name='unique_vcita_service_uid_per_account')],
            },
        ),
    ]
