# Generated by Django 6.0.7 on 2026-09-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcita', '0003_vcitaservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='vcitaaccount',
            name='external_booking_staff_uid',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vcitaservice',
            name='use_external_booking_staff',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
