# Generated by Django 6.0.7 on 2026-09-07 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0011_intakerequest_vcita_matter_uid_and_more'),
        ('lead', '0004_lead_vcita_client_uid'),
        ('vcita', '0004_vcitaaccount_external_booking_staff_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vcitaaccount',
            name='vcita_matter_name_field_uid',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='vcitawebhookevent',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('unmatched', 'Unmatched'), ('failed', 'Failed')], db_index=True, default='received', max_length=30),
        ),
        migrations.CreateModel(
            name='VcitaFinancialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('invoice', 'Invoice'), ('deposit', 'Deposit'), ('payment', 'Payment')], db_index=True, max_length=20)),
                ('vcita_uid', models.CharField(db_index=True, max_length=255)),
                ('matter_uid', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('unknown', 'Unknown'), ('issued', 'Issued'), ('pending', 'Pending'), ('paid', 'Paid'), ('recorded', 'Recorded'), ('updated', 'Updated'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='unknown', max_length=30)),
                ('amount', models.CharField(blank=True, default='', max_length=100)),
                ('currency', models.CharField(blank=True, default='', max_length=20)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_records', to='vcita.vcitaaccount')),
                ('intake', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vcita_financial_records', to='intake.intakerequest')),
                ('last_webhook_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_records', to='vcita.vcitawebhookevent')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vcita_financial_records', to='lead.lead')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['record_type', 'vcita_uid'], name='vcita_vcita_record__117a12_idx'), models.Index(fields=['matter_uid'], name='vcita_vcita_matter__18dcbf_idx'), models.Index(fields=['status', 'updated_at'], name='vcita_vcita_status_6804d0_idx'), models.Index(fields=['intake', 'record_type'], name='vcita_vcita_intake__a2e7d9_idx')],
                'constraints': [models.UniqueConstraint(fields=('account', 'record_type', 'vcita_uid'), name='unique_vcita_financial_record_uid')],
            },
        ),
    ]
