# Generated by Django 6.0.7 on 2026-09-08 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcita', '0005_vcitaaccount_vcita_matter_name_field_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vcitaservice',
            name='schedule_provider',
            field=models.CharField(choices=[('vcita', 'vCita'), ('google_only', 'Google Calendar only')], db_index=True, default='vcita', max_length=30),
        ),
    ]
