# Generated by Django 6.0.7 on 2026-09-05 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('intake', '0007_intakerequest_scheduled_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCalendarConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('calendar_type', models.CharField(choices=[('pending', 'Pending Appointments'), ('artist', 'Artist Calendar'), ('shared_vcita', 'Shared vCita Calendar')], db_index=True, max_length=30)),
                ('calendar_id', models.CharField(max_length=255, unique=True)),
                ('timezone', models.CharField(default='Europe/Amsterdam', max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='google_calendars', to='intake.artistprofile')),
            ],
            options={
                'ordering': ['calendar_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GoogleCalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('confirmed_appointment', 'Confirmed Appointment'), ('pending_hold', 'Pending Hold')], db_index=True, default='confirmed_appointment', max_length=40)),
                ('google_event_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('synced', 'Synced'), ('failed', 'Failed'), ('released', 'Released')], db_index=True, default='synced', max_length=30)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('summary', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('sync_error', models.TextField(blank=True, default='')),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='google_calendar.googlecalendarconfig')),
                ('intake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_calendar_events', to='intake.intakerequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='googlecalendarconfig',
            index=models.Index(fields=['calendar_type', 'is_active'], name='google_cale_calenda_66d5d4_idx'),
        ),
        migrations.AddIndex(
            model_name='googlecalendarconfig',
            index=models.Index(fields=['artist', 'is_active'], name='google_cale_artist__16bfa9_idx'),
        ),
        migrations.AddIndex(
            model_name='googlecalendarevent',
            index=models.Index(fields=['intake', 'event_type'], name='google_cale_intake__02ee34_idx'),
        ),
        migrations.AddIndex(
            model_name='googlecalendarevent',
            index=models.Index(fields=['calendar', 'status'], name='google_cale_calenda_79142a_idx'),
        ),
        migrations.AddIndex(
            model_name='googlecalendarevent',
            index=models.Index(fields=['google_event_id'], name='google_cale_google__ce5fc2_idx'),
        ),
    ]
