# Generated by Django 6.0.7 on 2026-08-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0003_conversation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='vcita_client_uid',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
